services:
  ffc-techspike-authentication:
    build:
      context: .
      target: production
    image: ffc-techspike-authentication
    container_name: ffc-techspike-authentication
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-authentication-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COOKIE_PASSWORD: cookiecookiecookiecookiecookiecookie
      DEFRAID_CLIENT_ID: ${DEFRAID_CLIENT_ID}
      DEFRAID_CLIENT_SECRET: ${DEFRAID_CLIENT_SECRET}
      DEFRAID_KNOWN_AUTHORITIES: ${DEFRAID_KNOWN_AUTHORITIES}
      DEFRAID_SCOPE: ${DEFRAID_SCOPE}
      DEFRAID_REDIRECT_URL: ${DEFRAID_REDIRECT_URL}
      DEFRAID_SIGNOUT_URL: ${DEFRAID_SIGNOUT_URL}
      DEFRAID_SIGNOUT_REDIRECT_URL: ${DEFRAID_SIGNOUT_REDIRECT_URL}
      DEFRAID_VALIDATE_AUTHORITY: ${DEFRAID_VALIDATE_AUTHORITY}
      DEFRAID_TENANT_NAME: ${DEFRAID_TENANT_NAME}
      DEFRAID_SERVICE_ID: ${DEFRAID_SERVICE_ID}
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      USE_HTTPS: ${USE_HTTPS}
