environment: production
environmentCode:
name: ffc-techspike-authentication
namespace: ffc-techspike
workstream: ffc-techspike
image: ffc-techspike-authentication

labels: {}

aadPodIdentity: true

appInsights:
  key:

azureIdentity:
  clientID:
  resourceID:

containerConfigMap:
  name: ffc-techspike-authentication-config-map

containerSecret:
  name: ffc-techspike-authentication-container-secret
  type: Opaque

deployment:
  cpuThreshold: 80
  memoryThreshold: 80
  minReadySeconds: 0
  minReplicas: 1
  maxReplicas: 1
  priorityClassName: high
  replicas: 1
  restartPolicy: Always

container:
  requestMemory: 100Mi
  requestCpu: 100m
  limitMemory: 100Mi
  limitCpu: 100m
  port: 3000
  cookiePassword: cookiecookiecookiecookiecookiecookie
  defraIdClientId:
  defraIdClientSecret:
  defraIdKnownAuthorities:
  defraIdRedirectUrl:
  defraIdSignoutUrl:
  defraIdSignoutRedirectUrl:
  defraIdValidateAuthority:
  defraIdTenantName:
  defraIdServiceId:
  redisHostname: redis-hostname.default
  redisPartition: ffc-techspike-authentication
  redisPassword: redis
  redisPort: 6379
  useHttps: false

service:
  port: 80
  type: ClusterIP

ingress:
  class: nginx
  endpoint: ffc-techspike-authentication
  server: example.com

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
