{{- include "ffc-helm-library.container-secret" (list . "ffc-techspike-authentication.container-secret") -}}
{{- define "ffc-techspike-authentication.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  DEFRAID_CLIENT_ID: {{ quote .Values.container.defraIdClientId }}
  DEFRAID_CLIENT_SECRET: {{ quote .Values.container.defraIdClientSecret }}
  DEFRAID_SERVICE_ID: {{ quote .Values.container.defraIdServiceId }}
{{- end -}}
