{{- include "ffc-helm-library.deployment" (list . "ffc-techspike-authentication.deployment") -}}
{{- define "ffc-techspike-authentication.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "ffc-helm-library.container" (list . "ffc-techspike-authentication.container") }}
{{- end -}}
